import { CalendarDays, ListChecks } from "lucide-react";
import { Link } from "react-router-dom";
import { useEvents } from "@/hooks/use-events";
import { useTasks } from "@/hooks/use-tasks";

/**
 * Everything the assistant has made, across all of the member's chats: the
 * events and tasks that carry an `aiRunId`. Read from the same lists the rest
 * of the app uses, so it shows exactly what the member can see elsewhere —
 * and it is mounted only while open, so those reads happen on demand.
 */
export function GeneratedPanel({ id }: { id: string }) {
  const tasks = useTasks();
  const events = useEvents();

  const loading = tasks.state.status === "loading" || events.state.status === "loading";
  const failed =
    tasks.state.status === "error"
      ? tasks.state.message
      : events.state.status === "error"
        ? events.state.message
        : undefined;
  const madeEvents =
    events.state.status === "ok" ? events.state.items.filter((event) => event.aiRunId) : [];
  const madeTasks =
    tasks.state.status === "ok" ? tasks.state.items.filter((task) => task.aiRunId) : [];

  return (
    <aside
      id={id}
      aria-label="Generated by the assistant"
      className="max-h-72 overflow-y-auto border-b bg-foreground/5 px-4 py-4 text-sm sm:px-6"
    >
      {loading && (
        <p className="text-muted-foreground" role="status">
          Loading what the assistant has made…
        </p>
      )}
      {failed && <p className="text-destructive">Couldn&apos;t load it: {failed}.</p>}
      {!loading && !failed && madeEvents.length + madeTasks.length === 0 && (
        <p className="text-muted-foreground">Nothing generated yet.</p>
      )}
      {!loading && !failed && madeEvents.length > 0 && (
        <section aria-labelledby={`${id}-events`}>
          <h3
            id={`${id}-events`}
            className="flex items-center gap-2 text-xs font-semibold text-muted-foreground uppercase"
          >
            <CalendarDays aria-hidden="true" className="size-3.5" />
            Events
          </h3>
          <ul className="mt-1 grid gap-1">
            {madeEvents.map((event) => (
              <li key={event.id}>
                <GeneratedLink to={`/events/${event.id}`}>{event.title}</GeneratedLink>
              </li>
            ))}
          </ul>
        </section>
      )}
      {!loading && !failed && madeTasks.length > 0 && (
        <section aria-labelledby={`${id}-tasks`} className={madeEvents.length > 0 ? "mt-4" : ""}>
          <h3
            id={`${id}-tasks`}
            className="flex items-center gap-2 text-xs font-semibold text-muted-foreground uppercase"
          >
            <ListChecks aria-hidden="true" className="size-3.5" />
            Tasks
          </h3>
          <ul className="mt-1 grid gap-1">
            {madeTasks.map((task) => (
              <li key={task.id}>
                {/* A task has no page of its own: it lives on its event's board, or the club's. */}
                <GeneratedLink to={task.eventId ? `/events/${task.eventId}?tab=tasks` : "/tasks"}>
                  {task.title}
                </GeneratedLink>
              </li>
            ))}
          </ul>
        </section>
      )}
    </aside>
  );
}

function GeneratedLink({ to, children }: { to: string; children: string }) {
  return (
    <Link to={to} className="rounded-sm underline underline-offset-4 hover:text-foreground">
      {children}
    </Link>
  );
}
